#!/usr/bin/env python3
"""
Generate Test Cases: Create pytest tests from sample questions.

Usage:
    python src/apps/generate_test_cases.py --input questions.json --output tests/test_generated.py
"""

import argparse
import json
from pathlib import Path
from typing import List, Dict


TEST_TEMPLATE = '''"""
Auto-generated test cases from sample questions.
Generated by: src/apps/generate_test_cases.py
"""

import pytest


class TestGeneratedQuestions:
    """Auto-generated tests from sample questions."""
    
{test_methods}
'''


METHOD_TEMPLATE = '''    def test_{test_name}(self):
        """{question}"""
        from src.guardrails.scope_guard import check_scope
        
        question = "{question}"
        is_valid, reason = check_scope(question)
        
        assert is_valid == {expected_in_scope}, f"Scope check failed: {{reason}}"
'''


def generate_test_name(question: str, index: int) -> str:
    """Generate a valid test method name."""
    # Take first few words, remove special chars
    words = question.lower().split()[:5]
    name = "_".join(w for w in words if w.isalnum())
    return f"{index:03d}_{name}"


def generate_tests(questions: List[Dict]) -> str:
    """Generate test file content from questions."""
    
    methods = []
    for i, q in enumerate(questions):
        question = q.get("question", q) if isinstance(q, dict) else q
        expected_in_scope = not q.get("expected_out_of_scope", False) if isinstance(q, dict) else True
        
        test_name = generate_test_name(question, i)
        method = METHOD_TEMPLATE.format(
            test_name=test_name,
            question=question.replace('"', '\\"'),
            expected_in_scope=expected_in_scope
        )
        methods.append(method)
    
    return TEST_TEMPLATE.format(test_methods="\n".join(methods))


def main():
    parser = argparse.ArgumentParser(description="Generate pytest test cases")
    parser.add_argument("--input", help="Input JSON file with questions")
    parser.add_argument("--output", default="tests/test_generated.py", help="Output test file")
    
    args = parser.parse_args()
    
    # Load questions or use defaults
    if args.input and Path(args.input).exists():
        with open(args.input) as f:
            questions = json.load(f)
    else:
        questions = [
            {"question": "What is the total deposit amount?", "expected_out_of_scope": False},
            {"question": "How many transactions by channel?", "expected_out_of_scope": False},
            {"question": "What's the weather today?", "expected_out_of_scope": True},
        ]
    
    # Generate tests
    test_content = generate_tests(questions)
    
    # Write output
    output_path = Path(args.output)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(test_content)
    
    print(f"Generated {len(questions)} test cases: {output_path}")


if __name__ == "__main__":
    main()
